src/objects/BR_Event__c.object
<CustomObject>

    <fields>
        <fullName>Send_reminders__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send reminders</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>AC Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AC Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BrEventTriggerHandler.cls
public with sharing class BrEventTriggerHandler {
    public BrEventTriggerHandler() {}

    public void onBeforeUpdate(BR_Event__c[] changedEvents, Map<Id, BR_Event__c > oldMapEvents) {
        Set<Id> eventIds = new Set<Id>();

        for (BR_Event__c event : changedEvents) {
            BR_Event__c oldEvent = oldMapEvents.get(event.Id);

            if (oldEvent.Start_Date__c != event.Start_Date__c || oldEvent.Send_reminders__c != event.Send_reminders__c) {
                eventIds.add(event.Id);
            }
            else {
                return;
            }
        }

        BrEventsHelper.updateParticipateOnChangeEventDate(eventIds);
    }
}