src/objects/BR_Event__c.object
<CustomObject>

    <fields>
        <fullName>Send_reminders__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Send reminders</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>AC Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AC Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BrEvents_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Label__c</fullName>
        <description>Settings variable label</description>
        <inlineHelpText>Settings variable label</inlineHelpText>
        <label>Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Events Settings</label>
</CustomObject>

src/classes/BrEventCommunityLinkCtrlTest.cls
@IsTest
private class BrEventCommunityLinkCtrlTest {
    static testMethod void testGetCommunityLink() {
        DateTime startDate = DateTime.now();
        BR_Event__c event = new BR_Event__c(Name = 'testEvent', Start_Date__c = startDate, Send_reminders__c = true);

        insert event;

        String communityId = [SELECT Id FROM Network LIMIT 1].Id;

        insert new BrEvents_Settings__c(Name='community', Label__c = 'Community', Value__c = communityId);

        BrEventCommunityLinkCtrl ctrl = new BrEventCommunityLinkCtrl();
        ctrl.eventId = event.Id;
        System.assertNotEquals(null, ctrl.getCommunityLink(), 'Community link is empty');
    }
}