src/objects/BR_Event__c.object
<CustomObject>

    <label>AC Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AC Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BR_Participation__c.object
<CustomObject>

    <fields>
        <fullName>BR_Event__c</fullName>
        <label>BR Event</label>
        <referenceTo>BR_Event__c</referenceTo>
        <relationshipName>BR_Participations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Participate__c</fullName>
        <label>Participate</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Maybe</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>BR_Participations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AC Participation</label>
    <nameField>
        <displayFormat>P-{0000000}</displayFormat>
        <label>Participation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/BrEventsListItemController.cls
public with sharing class BrEventsListItemController {

    @AuraEnabled
    public static String rsvpEvent(Id recordId, String rsvpType, Integer attendeesLimit){
        if(String.isBlank(recordId) || String.isBlank(rsvpType)){
            return 'error';
        }

        if (UserInfo.getUserType() == 'Guest')
            return 'auth_required';

        List<String> participationFieldsToUpdate = new List<String>();
        participationFieldsToUpdate.add('Participate__c');
        List<String> participationFieldsToCreate = new List<String>();
        participationFieldsToCreate.add('BR_Event__c');
        participationFieldsToCreate.add('Participate__c');
        participationFieldsToCreate.add('User__c');

        if(!BrEventsHelper.performAccessCheck('read', 'BR_Participation__c', null)
                || !BrEventsHelper.performAccessCheck('edit', 'BR_Participation__c', participationFieldsToUpdate)
                || !BrEventsHelper.performAccessCheck('create', 'BR_Participation__c', participationFieldsToCreate)){
            return 'error';
        }

        String count_query = 'SELECT COUNT() FROM BR_Participation__c WHERE BR_Event__c = \'' + recordId + '\' AND Participate__c  = \'Yes\'';

        attendeesLimit = Integer.valueOf(attendeesLimit);

        if(attendeesLimit != 0 && rsvpType == 'Yes'){
            Integer attendeesCount = Database.countQuery(count_query);

            if(attendeesCount != 0 && attendeesCount >= attendeesLimit){
                return 'limit_exceded';
            }

        }

        List<BR_Participation__c> participations = [SELECT Id FROM BR_Participation__c
        WHERE BR_Event__c = :recordId
        AND User__c = :UserInfo.getUserId() LIMIT 1];

        BR_Participation__c p = new BR_Participation__c();

        if(participations.size() > 0){
            p = participations[0];
            p.Participate__c = rsvpType;
        } else {
            p.BR_Event__c = recordId;
            p.Participate__c = rsvpType;
            p.User__c = UserInfo.getUserId();
        }

        try {
            upsert p;

            return String.valueOf(Database.countQuery(count_query));
        }
        catch (DmlException e) {
            System.debug(e.getMessage());

            return 'error';
        }
    }
}