src/objects/BR_Event__c.object
<CustomObject>

    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <label>AC Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AC Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BrEventStartDateCtrlTest.cls
@isTest
public with sharing class EventStartDateCtrlTest {
    static testMethod void testGetStartDateFormatted() {
        DateTime startDate = DateTime.now();
        BR_Event__c event = new BR_Event__c(Name = 'testEvent', Start_Date__c = startDate
        );

        insert event;

        BrEventStartDateCtrl ctrl = new BrEventStartDateCtrl();
        ctrl.startDate = event.Start_Date__c;
        ctrl.timezone = 'Europe/Minsk';
        ctrl.locale = 'be_BY';

        System.assertNotEquals('28.04.2017 21:18', ctrl.getStartDateFormatted(), 'Formatted start date for event');
    }
}