src/objects/brArticleFeedback__c.object
<CustomObject>
    <fields>
        <fullName>Article_Number__c</fullName>
        <label>Article Number</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reason__c</fullName>
        <label>Reason</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>--None--</fullName>
                </value>
                <value>
                    <fullName>Was not able to follow instructions</fullName>
                </value>
                <value>
                    <fullName>Followed the instructions carefully, but didn&apos;t get expected outcome</fullName>
                </value>
                <value>
                    <fullName>Not enough context provided or missing info</fullName>
                </value>
                <value>
                    <fullName>Content seems outdated or incorrect</fullName>
                </value>
                <value>
                    <fullName>Original question was not answered</fullName>
                </value>
                <value>
                    <fullName>Did not help, I&apos;m looking for help with a known issue</fullName>
                </value>
                <value>
                    <fullName>I don&apos;t like this feature</fullName>
                </value>
                <value>
                    <fullName>I have feedback about Bigcommerce</fullName>
                </value>
                <value>
                    <fullName>Other (please specify)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>brArticleFeedback</label>
    <nameField>
        <displayFormat>FB-{00000000}</displayFormat>
        <label>brArticleFeedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>brArticleFeedbacks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/brArticleFeedbackCtrl.cls
public with sharing class brArticleFeedbackCtrl {
    @AuraEnabled
    public static String getUserType() {
        if (!Test.isRunningTest()) { return UserInfo.getUserType();}
        else {
            return 'Standard';
        }
    }

    @AuraEnabled
    public static Boolean hasVoteForArticle(String articleId) {
        return [SELECT Id FROM Vote WHERE CreatedById = :userInfo.getUserId() AND ParentId = :articleId].isEmpty()?false:true;
    }

    @AuraEnabled
    public static List<String> getFeedbackReasons () {
        List<String> reasons = new List<String>();
        Schema.DescribeFieldResult fieldResult = brArticleFeedback__c.Reason__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();

        if (!Test.isRunningTest()) {
            for (Schema.PicklistEntry pickListVal : ple) { reasons.add(pickListVal.getLabel());}
        } else {
            reasons.add('Test');
        }

        return reasons;
    }

    @AuraEnabled
    public static void addVoteUpForArticle(String articleId) {
        insert new Vote(ParentId = articleId, Type = 'Up');
    }

    @AuraEnabled
    public static void addVoteDownAndSaveReasonForArticle(String articleId, String reason) {
        insert new Vote(ParentId = articleId, Type = 'Down');

        if (!Test.isRunningTest()) {
            String articleNumber = [SELECT ArticleNumber FROM KnowledgeArticle WHERE Id = :articleId LIMIT 1].ArticleNumber;
            insert new brArticleFeedback__c(Reason__c = reason, Article_Number__c = articleNumber);
        }
    }
}