src/objects/brBlog_article__c.object
<CustomObject>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Published_Date__c</fullName>
        <label>Published Date</label>
        <type>DateTime</type>
    </fields>
    <label>Blog Article</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blog Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/brBlog_Category__c.object
<CustomObject>
    <fields>
        <fullName>Friendly_URL__c</fullName>
        <label>Friendly URL</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Blog Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blog Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/brCategory_assignment__c.object
<CustomObject>
    <fields>
        <fullName>Blog_Article__c</fullName>
        <label>Blog Article</label>
        <referenceTo>brBlog_article__c</referenceTo>
        <relationshipLabel>Blog Categories</relationshipLabel>
        <relationshipName>Category_Assignment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Blog_Category__c</fullName>
        <label>Blog Category</label>
        <referenceTo>brBlog_Category__c</referenceTo>
        <relationshipLabel>Blog Articles</relationshipLabel>
        <relationshipName>Category_Assignment</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <formula>Blog_Article__r.Draft__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <label>Blog Category Assignment</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blog Category Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/brBlogCategoriesCtrl.cls
public with sharing class brBlogCategoriesCtrl {

    @AuraEnabled
    public static List<AggregateResult> getCategories() {

        // CRUD/FLS enforcement check
        if(!brBlogHelper.performAccessCheck('read', 'brBlog_article__c', new List<String>{'Published_Date__c', 'Draft__c'})
                || !brBlogHelper.performAccessCheck('read', 'brBlog_Category__c', new List<String>{'Friendly_URL__c'})
                || !brBlogHelper.performAccessCheck('read', 'brCategory_Assignment__c', new List<String>{'Blog_Category__c'})){
            return null;
        }

        String currentTimeGMT = DateTime.now().formatGmt('YYYY-MM-dd\'T\'HH:mm:ss\'Z\'');

        String query = 'SELECT Blog_Category__r.Name categoryName, MIN(Blog_Category__r.Friendly_URL__c) urlName,' +
                ' COUNT(Blog_Category__c) categoryCount' +
                ' FROM brCategory_assignment__c' +
                ' WHERE Blog_Article__r.Draft__c = false' +
                ' AND Blog_Article__r.Published_Date__c < ' + currentTimeGMT +
                ' GROUP BY Blog_Category__r.Name';

        return Database.query(query);
    }
}