src/objects/brBlog_article__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Published_Date__c</fullName>
        <label>Published Date</label>
        <type>DateTime</type>
    </fields>
    <label>Blog Article</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blog Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/brBlog_Category__c.object
<CustomObject>
    <fields>
        <fullName>Friendly_URL__c</fullName>
        <label>Friendly URL</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Blog Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blog Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/brBlog_Tag__c.object
<CustomObject>
    <fields>
        <fullName>Friendly_URL__c</fullName>
        <label>Friendly URL</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Blog Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blog Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/brBlog_Tag_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Blog_Article__c</fullName>
        <label>Blog Article</label>
        <referenceTo>brBlog_article__c</referenceTo>
        <relationshipLabel>Blog Tags</relationshipLabel>
        <relationshipName>Blog_Tag_Assignment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Blog_Tag__c</fullName>
        <label>Blog Tag</label>
        <referenceTo>brBlog_Tag__c</referenceTo>
        <relationshipLabel>Blog Articles</relationshipLabel>
        <relationshipName>Blog_Tag_Assignment</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Blog Tag Assignment</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tag Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blog Tag Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/brCategory_assignment__c.object
<CustomObject>
    <fields>
        <fullName>Blog_Article__c</fullName>
        <label>Blog Article</label>
        <referenceTo>brBlog_article__c</referenceTo>
        <relationshipLabel>Blog Categories</relationshipLabel>
        <relationshipName>Category_Assignment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Blog_Category__c</fullName>
        <label>Blog Category</label>
        <referenceTo>brBlog_Category__c</referenceTo>
        <relationshipLabel>Blog Articles</relationshipLabel>
        <relationshipName>Category_Assignment</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <formula>Blog_Article__r.Draft__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <label>Blog Category Assignment</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blog Category Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/brBlogArticleDetailCtrl.cls
public with sharing class brBlogArticleDetailCtrl {

    @AuraEnabled
    public static brBlogArticleWrapper getArticle(Id articleId) {
        brBlogArticleWrapper articleWrapped = new brBlogArticleWrapper();

        // CRUD/FLS enforcement check
        if(!brBlogHelper.performAccessCheck('read', 'brBlog_article__c', new List<String>{'Body__c', 'Published_Date__c', 'Draft__c'})
                || !brBlogHelper.performAccessCheck('read', 'brBlog_Category__c', new List<String>{'Friendly_URL__c'})
                || !brBlogHelper.performAccessCheck('read', 'brBlog_Tag__c', new List<String>{'Friendly_URL__c'})
                || !brBlogHelper.performAccessCheck('read', 'brCategory_Assignment__c', null)
                || !brBlogHelper.performAccessCheck('read', 'brBlog_Tag_Assignment__c', null)){
            return articleWrapped;
        }

        List<brBlog_article__c> articles = [SELECT Id, Name, Owner.Id, OwnerId, Owner.Name, Body__c, Published_Date__c, Draft__c,
                                                        (SELECT Id, Blog_Category__r.Name, Blog_Category__r.Friendly_URL__c
                                                        FROM Category_Assignment__r),
                                                        (SELECT Id, Blog_Tag__r.Name, Blog_Tag__r.Friendly_URL__c
                                                        FROM Blog_Tag_Assignment__r)
                                                    FROM brBlog_article__c
                                                    WHERE Id = :articleId];

        if (articles.size() < 1) {
            return articleWrapped;
        }

        Set<Id> userId = new Set<Id>();
        userId.add(articles.get(0).OwnerId);

        articleWrapped.item = articles.get(0);
        articleWrapped.categories = brBlogHelper.getArticleCategories(articles.get(0).Category_Assignment__r);
        articleWrapped.tags = brBlogHelper.getArticleTags(articles.get(0).Blog_Tag_Assignment__r);
        articleWrapped.commentsNumber = brBlogHelper.getCommentsNumber(articleId);
        articleWrapped.profilePhotoUrl = brBlogHelper.getProfilePhotoUrl(userId).get(articles.get(0).OwnerId);

        return articleWrapped;
    }
}