src/objects/brBlog_article__c.object
<CustomObject>
    <fields>
        <fullName>Draft__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Published_Date__c</fullName>
        <label>Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Short_Body__c</fullName>
        <label>Short Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <label>Blog Article</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blog Articles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/brBlog_Category__c.object
<CustomObject>
    <fields>
        <fullName>Friendly_URL__c</fullName>
        <label>Friendly URL</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Blog Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blog Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/brBlog_Tag__c.object
<CustomObject>
    <fields>
        <fullName>Friendly_URL__c</fullName>
        <label>Friendly URL</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Blog Tag</label>
    <nameField>
        <label>Tag Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Blog Tags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/brBlog_Tag_Assignment__c.object
<CustomObject>
    <fields>
        <fullName>Blog_Article__c</fullName>
        <label>Blog Article</label>
        <referenceTo>brBlog_article__c</referenceTo>
        <relationshipLabel>Blog Tags</relationshipLabel>
        <relationshipName>Blog_Tag_Assignment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Blog_Tag__c</fullName>
        <label>Blog Tag</label>
        <referenceTo>brBlog_Tag__c</referenceTo>
        <relationshipLabel>Blog Articles</relationshipLabel>
        <relationshipName>Blog_Tag_Assignment</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Blog Tag Assignment</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Tag Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blog Tag Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/brCategory_assignment__c.object
<CustomObject>
    <fields>
        <fullName>Blog_Article__c</fullName>
        <label>Blog Article</label>
        <referenceTo>brBlog_article__c</referenceTo>
        <relationshipLabel>Blog Categories</relationshipLabel>
        <relationshipName>Category_Assignment</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Blog_Category__c</fullName>
        <label>Blog Category</label>
        <referenceTo>brBlog_Category__c</referenceTo>
        <relationshipLabel>Blog Articles</relationshipLabel>
        <relationshipName>Category_Assignment</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Draft__c</fullName>
        <formula>Blog_Article__r.Draft__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Draft</label>
        <type>Checkbox</type>
    </fields>
    <label>Blog Category Assignment</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Category Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Blog Category Assignment</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/brBlogTestUtils.cls
@IsTest
public class brBlogTestUtils {
    public static List<brBlog_article__c> testCreateArticles() {
        List<brBlog_article__c> articles = new List<brBlog_article__c>();

        for (Integer i = 0; i < 3; i++) {

            articles.add(new brBlog_article__c(Name = 'What is Salesforce',
                    Short_Body__c = 'Salesforce  is an American cloud computing company',
                    Draft__c = false,
                    Published_Date__c = Datetime.newInstance(2016, 10, 15, 12, 30, 0)
            ));
        }

        insert articles;

        System.assertEquals('What is Salesforce', articles[0].Name, 'get first article name value');

        return articles;
    }

    public static List<brBlog_Tag__c> testCreateTags() {
        List<brBlog_Tag__c> tags = new List<brBlog_Tag__c>();

        for (Integer i = 0; i < 3; i++) {
            tags.add(new brBlog_Tag__c(Name = 'SalesforceTag' + i));
        }

        insert tags;

        System.assertEquals('SalesforceTag0', tags[0].Name, 'get first tag name value');

        return tags;
    }

    public static List<brBlog_Category__c> testCreateCategories() {
        List<brBlog_Category__c> categories = new List<brBlog_Category__c>();

        for (Integer i = 0; i < 3; i++) {
            categories.add(new brBlog_Category__c(Name = 'SalesforceCategory' + i));
        }

        insert categories;

        System.assertEquals('SalesforceCategory0', categories[0].Name, 'get first category name value');

        return categories;
    }

    public static void testCreateTagsAssignment() {
        List<brBlog_Tag__c> tags = [SELECT Id, Name FROM brBlog_Tag__c LIMIT 150];
        List<brBlog_article__c> articles = [SELECT Id, Name FROM brBlog_article__c LIMIT 150];
        List<brBlog_Tag_Assignment__c> tagsAssignment = new List<brBlog_Tag_Assignment__c>();

        for (brBlog_article__c article : articles) {
            for (brBlog_Tag__c tag : tags) {
                tagsAssignment.add(new brBlog_Tag_Assignment__c(Blog_Article__c = article.Id,
                        Blog_Tag__c = tag.Id));
            }
        }

        insert tagsAssignment;

        System.assertNotEquals(null, tagsAssignment, 'tags assignment exist');
    }

    public static void testCreateCategoriesAssignment() {
        List<brBlog_article__c> articles = [SELECT Id, Name FROM brBlog_article__c LIMIT 150];
        List<brBlog_Category__c> categories = [SELECT Id, Name, Friendly_URL__c
        FROM brBlog_Category__c LIMIT 150];

        List<brCategory_assignment__c> categoriesAssignment = new List<brCategory_assignment__c>();

        for (brBlog_article__c article : articles) {
            for (brBlog_Category__c category : categories) {
                categoriesAssignment.add(new brCategory_assignment__c(Blog_Article__c = article.Id,
                        Blog_Category__c = category.Id));
            }
        }

        insert categoriesAssignment;

        System.assertNotEquals(null, categoriesAssignment, 'categories assignment exist');
    }

    public static void testCreateUser() {
        Profile p = [SELECT Id FROM Profile WHERE Name='Standard User'];
        User user = new User(Alias = 'standt', Email='standarduser@testorg.com',
                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                LocaleSidKey='en_US', ProfileId = p.Id,
                TimeZoneSidKey='America/Los_Angeles', UserName='standardusekjnkjnr@testorg.com');
        insert user;
        assignPermissionSet(user.Id, 'AC_Blog_User');

        System.assertEquals('standardusekjnkjnr@testorg.com', user.Username, 'get user name value');
    }

    public static void testCreateExternalUser() {
        Account account = new Account(Name ='Graz') ;
        insert account;

        Contact contact = new Contact(LastName = 'Barry', AccountId = account.Id);
        insert contact;

        Profile p = [SELECT Id FROM Profile WHERE Name='Customer Community User'];
        User user = new User(Alias = 'standt', Email='externaluser@testorg.com',
                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US',
                LocaleSidKey='en_US', ProfileId = p.Id, ContactId = contact.Id,
                TimeZoneSidKey='America/Los_Angeles', UserName='externaluser@testorg.com');

        insert user;
        assignPermissionSet(user.Id, 'AC_Blog_User');

        System.assertEquals('externaluser@testorg.com', user.Username, 'get user name value');
    }

    @future
    public static void assignPermissionSet(Id userId, String permissionSet) {
        PermissionSet ps = [SELECT Id From PermissionSet WHERE Name = :permissionSet];
        insert new PermissionSetAssignment(AssigneeId = userId, PermissionSetId = ps.Id);

        System.assertNotEquals(null, ps, 'permission set not null');
    }

    public static void testCreateEmailTemplate() {

        EmailTemplate emailTemplate = new EmailTemplate (TemplateType= 'Text', FolderId = UserInfo.getUserId(),
                Name = 'Blog Moderation', Body = '{!User.FirstName} {!User.LastName} {!Blog_article__c.Link}');
        insert emailTemplate;

        System.assertNotEquals(null, emailTemplate, 'not null email template object');
    }
}