src/objects/BrEvents_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Events Settings</label>
</CustomObject>

src/classes/BrEventCommunityLinkCtrl.cls
public with sharing class BrEventCommunityLinkCtrl {
        public String eventId {get; set;}

    public BrEventCommunityLinkCtrl() {}

    public String getCommunityLink() {
        //BrEvents_Settings__c communityRow = [SELECT Value__c FROM BrEvents_Settings__c WHERE Name = 'community'];
//        String instanceUrl = Network.getLoginUrl('0DBi0000000XZOEGA4').replace('login', '');
//
//        return ' ' + instanceUrl + 'events#' + eventId;

        return '';
    }
}