src/objects/BrEvents_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Label__c</fullName>
        <description>Settings variable label</description>
        <inlineHelpText>Settings variable label</inlineHelpText>
        <label>Label</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Events Settings</label>
</CustomObject>

src/classes/BrEventsInstallHandler.cls
global class BrEventsInstallHandler implements InstallHandler {
    global void onInstall(InstallContext context) {
        if(context.previousVersion() == null) {
            this.setImageSourceSettings('files');
        }
        else {
            this.setImageSourceSettings('attachments');
        }
    }

    private void setImageSourceSettings(String imageSource) {
        if (!BrEventsHelper.performAccessCheck('read', 'BrEvents_Settings__c', null))
            return;

        List<BrEvents_Settings__c> settings = [SELECT Id FROM BrEvents_Settings__c WHERE Name = 'image source'];

        if (settings.size() == 0 && BrEventsHelper.performAccessCheck('create', 'BrEvents_Settings__c', null)) {
            insert new BrEvents_Settings__c(Name='image source', Label__c = 'Image Source', Value__c = imageSource);
        }
    }
}