src/objects/brPhoneSupportList__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>brPhone Support List</label>
</CustomObject>

src/classes/brMobileNavMenuCtrlTest.cls
@isTest
private class brMobileNavMenuCtrlTest {
    static testMethod void brMobileNavMenuCtrlTest() {
    	
    	brPhoneSupportList__c phone = new brPhoneSupportList__c();
    	phone.Country__c = 'US';
    	phone.Phone__c = '1111111';
    	phone.Name = 'US';
    	insert phone;
    	
    	Test.startTest();
    		System.assertEquals(1,brMobileNavMenuCtrl.getPhoneList().size());
    		System.assertEquals(UserInfo.getUserId(),Id.valueOF(brMobileNavMenuCtrl.getUserInfo().id));
    	Test.stopTest();
    }
}