src/objects/Learning__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>This article type contains the learning guides for the support site.</description>
    <fields>
        <fullName>Nav_Title__c</fullName>
        <description>This field should contain the title used in the left navigation to be set as active</description>
        <inlineHelpText>Enter the navigation title from the left menu that should be active</inlineHelpText>
        <label>Nav Title</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Learning</label>
    <pluralLabel>Learning</pluralLabel>
</CustomObject>

src/objects/University__kav.object
<CustomObject>
    <fields>
        <fullName>Sort_Oder_in_Category__c</fullName>
        <label>Sort Oder in Category</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Video</label>
    <pluralLabel>Videos</pluralLabel>
</CustomObject>

src/classes/brCategoriesCatalogService.cls
public with sharing class brCategoriesCatalogService {
    
    public static List<brCategoriesCatalogModel> getCatalog(String articleType) {

        if (articleType == 'University__kav') {
            brSecurityService.performAccessCheck('read', articleType, new List<String>{
                'KnowledgeArticleId', 'Title', 'Nav_Title__c','Sort_Oder_in_Category__c','PublishStatus'});
        } else {
            brSecurityService.performAccessCheck('read', articleType, new List<String>{
                'KnowledgeArticleId', 'Title', 'Nav_Title__c','Sort_Oder_in_Category__c','PublishStatus','Section_Anchors__c'});
        }
        brSecurityService.performAccessCheck('read', articleType.replace('__kav','') + '__DataCategorySelection', new List<String>{
                'ParentId','DataCategoryGroupName','DataCategoryName'});

        Map<String, List<brArticleModel>> catsArticlesMap = new Map<String, List<brArticleModel>>();
        List<SObject> articlesList = brCategoriesCatalogServiceSelector.getArticles(articleType);
        String dataCategoryGroupName = '';

        for (SObject ar: articlesList) {
            if(ar.getSObjects('DataCategorySelections') == null) continue;

            if(String.isBlank(dataCategoryGroupName)) {
                dataCategoryGroupName = String.valueOf(articlesList[0].getSObjects('DataCategorySelections')[0].get('DataCategoryGroupName'));
            }

            String dataCategory = String.valueOf(ar.getSObjects('DataCategorySelections')[0].get('DataCategoryName'));

            brArticleModel am = new brArticleModel();
            am.UrlName = String.valueOf(ar.get('UrlName'));

            if(ar.get('Nav_Title__c') != null) {
                am.title = String.valueOf(ar.get('Nav_Title__c'));
            } else {
                am.title = String.valueOf(ar.get('Title'));
            }

            am.id = String.valueOf(ar.get('KnowledgeArticleId'));
            am.article_id = String.valueOf(ar.get('Id'));

            if(!catsArticlesMap.containsKey(dataCategory)) {
                catsArticlesMap.put(dataCategory, new List<brArticleModel>());
            }

            List<brArticleModel> articlesForCategory = catsArticlesMap.get(dataCategory);
            articlesForCategory.add(am);
            catsArticlesMap.put(dataCategory, articlesForCategory);
        }

        List<brCategoriesCatalogModel> catCatalogList = brCategoryService.getAllCategoriesForGroup(dataCategoryGroupName);

        for(brCategoriesCatalogModel ccm : catCatalogList) {
            ccm.isNumeric = (articleType == 'Learning__kav');

            if(catsArticlesMap.containsKey(ccm.id)) {
                ccm.articles = catsArticlesMap.get(ccm.id);
            }

            for(brCategoriesCatalogModel subccm : ccm.categories) {
                if(catsArticlesMap.containsKey(subccm.id)) {
                    subccm.articles = catsArticlesMap.get(subccm.id);
                }

                for(brCategoriesCatalogModel subsubccm : subccm.categories) {
                    if(catsArticlesMap.containsKey(subsubccm.id)) {
                        subsubccm.articles =  catsArticlesMap.get(subsubccm.id);
                    }
                }
            }
        }

        return catCatalogList;
    }
    
}