src/objects/Learning__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>This article type contains the learning guides for the support site.</description>
    <fields>
        <fullName>Nav_Title__c</fullName>
        <description>This field should contain the title used in the left navigation to be set as active</description>
        <inlineHelpText>Enter the navigation title from the left menu that should be active</inlineHelpText>
        <label>Nav Title</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Learning</label>
    <pluralLabel>Learning</pluralLabel>
</CustomObject>

src/objects/Public__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <fields>
        <fullName>Nav_Title__c</fullName>
        <label>Nav Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Public</label>
    <pluralLabel>Public</pluralLabel>
</CustomObject>

src/classes/brCategoriesTest.cls
@isTest
private class brCategoriesTest {

    static testMethod void tMethod() {

        Learning__kav article = new Learning__kav(Title = 'Test', Nav_Title__c = 'Test', UrlName = 't321est');
        insert article;

        for (Learning__kav uKav : [SELECT KnowledgeArticleId FROM Learning__kav WHERE Id = :article.Id]) {
            KbManagement.PublishingService.publishArticle(uKav.KnowledgeArticleId, true);
        }

        Learning__kav article1 = new Learning__kav(Title = 'Test1', Nav_Title__c = 'Test', UrlName = 'te213st1');
        insert article1;

        for (Learning__kav uKav : [SELECT KnowledgeArticleId FROM Learning__kav WHERE Id = :article1.Id]) {
            KbManagement.PublishingService.publishArticle(uKav.KnowledgeArticleId, true);
        }

        Learning__DataCategorySelection tempCat = new Learning__DataCategorySelection();
        tempCat.DataCategoryGroupName = 'Guides';
        tempCat.DataCategoryName = 'Inventory_management';
        tempCat.ParentId = article.id;


        insert tempCat;

        Public__kav article2 = new Public__kav(Title = 'Test1', Nav_Title__c = 'Test', UrlName = 'tes231123312t1', Section_Anchors__c = 'asdsafds:sdfsdf;dsafasfd:sdfsdf;');
        insert article2;

        for (Public__kav uKav : [SELECT KnowledgeArticleId FROM Public__kav WHERE Id = :article2.Id]) {
            KbManagement.PublishingService.publishArticle(uKav.KnowledgeArticleId, true);
        }

        Public__DataCategorySelection tempCat1 = new Public__DataCategorySelection();
        tempCat1.DataCategoryGroupName = 'Public';
        tempCat1.DataCategoryName = 'Configure_Your_Store';
        tempCat1.ParentId = article2.id;

        insert tempCat1;

        Test.startTest();
        List<Public__kav> pubList = [SELECT KnowledgeArticleId, UrlName FROM Public__kav WHERE Id = :article2.Id];
        List<Learning__kav> gdList = [SELECT KnowledgeArticleId, UrlName FROM Learning__kav WHERE Id = :article1.Id];
        brCategoriesController.getCatalog(article.id, 'Learning__kav', tempCat.DataCategoryGroupName, gdList[0].UrlName);
        brCategoriesController.getCatalog(article2.id, 'Public__kav', tempCat1.DataCategoryGroupName, pubList[0].UrlName);
        brCategoriesCatalogServiceSelector.getArticleCategories('test');
        brCategoryServiceSelector.getCategories('Inventory_management');
        brCategoryServiceSelector.getFirstCategories('Inventory_management');
        brCategoryServiceSelector.getSubCategories('Inventory_management');
        brCategoryServiceSelector.getCategories('Payments');
        brCategoryServiceSelector.getFirstCategories('Payments');
        brCategoryServiceSelector.getSubCategories('Payments');
        brCategoryServiceSelector.getCategories('Live_Chat');
        brCategoryServiceSelector.getFirstCategories('Live_Chat');
        brCategoryServiceSelector.getSubCategories('Live_Chat');
        Test.stopTest();
    }

}